name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "Deploying to staging cluster"
          echo "${{ secrets.SSH_KEY }}" &> ~/ssh_key
          mkdir -p /home/ubuntu/.ssh
          ls /home/ubuntu/.ssh
          touch /home/ubuntu/.ssh/known_hosts
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" &> /home/ubuntu/.ssh/known_hosts
          chmod 700 /home/ubuntu/ssh_key
          ssh -i ~/ssh_key root@64.227.147.124 -t "cd week-25-ci-next-app/ 
          && git pull origin main 
          
