name: Deploy on staging env
on : 
  push : 
    branches : 
      - main

jobs: 
  uses: ubuntu-latest
  redeploying-everything: 
    name:  Deploying everything to staging env
    steps: 
      name : Deploying to staging env
      run: | 
        echo "Deploying to staging environment..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_KNOWN_HOSTS }} >> ~/.ssh/known_hosts
        ssh ubuntu@${{ secrets.SSH_KNOWN_HOSTS }} 'bash -s' <<'ENDSSH'
        echo "Connected to server!"
            cd ci-cd-monorepo
            git pull origin main
            pnpm install


